--Creates the two tables with their foreign key constraints

/*
Stores the ecrypted texts that should be processed

-id autogenerated integer key
-encrypted_text text the encrypted text entered from the user
*/
CREATE TABLE texts (
    id SERIAL PRIMARY KEY,
    encrypted_text text UNIQUE NOT NULL
);

/*
Stores the decrypting tasks that should be done by the workers and their results

-id autogenerated integer key
-text_id integer foreign key to the text from texts tables
-from_key string the first key in the interval that should be processed
-to_key the string last key in the interval that should be processed
-accepted_timestamp bigint the timestamp in unixtime format in which a worker accepted the task
-best_key string the key which generated the best confidence score
-confidence numeric the confidence score stating the probabilty that the decrypted text is actually the original clear text
*/
CREATE TABLE tasks (
    id SERIAL PRIMARY KEY,
    text_id integer REFERENCES texts,
    from_key text NOT NULL,
    to_key text NOT NULL,
    accepted_timestamp bigint,
    best_key text,
    confidence numeric
);